[<tf.Variable 'Variable:0' shape=(3, 49, 49) dtype=float32_ref>, 
<tf.Variable 'model/stgcn_var/batch_normalization/gamma:0' shape=(147,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/batch_normalization/beta:0' shape=(147,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/batch_normalization/moving_mean:0' shape=(147,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/batch_normalization/moving_variance:0' shape=(147,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/conv_temporal_graphical/conv2d/kernel:0' shape=(1, 1, 3, 192) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/conv_temporal_graphical/conv2d/bias:0' shape=(192,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/batch_normalization_1/gamma:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/batch_normalization_1/beta:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/batch_normalization_1/moving_mean:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/batch_normalization_1/moving_variance:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/conv2d_1/kernel:0' shape=(9, 1, 64, 64) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/conv2d_1/bias:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/batch_normalization_2/gamma:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/batch_normalization_2/beta:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/batch_normalization_2/moving_mean:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn/sequential/batch_normalization_2/moving_variance:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/conv_temporal_graphical_1/conv2d_2/kernel:0' shape=(1, 1, 64, 192) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/conv_temporal_graphical_1/conv2d_2/bias:0' shape=(192,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/batch_normalization_3/gamma:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/batch_normalization_3/beta:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/batch_normalization_3/moving_mean:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/batch_normalization_3/moving_variance:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/conv2d_3/kernel:0' shape=(9, 1, 64, 64) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/conv2d_3/bias:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/batch_normalization_4/gamma:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/batch_normalization_4/beta:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/batch_normalization_4/moving_mean:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_1/sequential_1/batch_normalization_4/moving_variance:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/conv_temporal_graphical_2/conv2d_4/kernel:0' shape=(1, 1, 64, 192) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/conv_temporal_graphical_2/conv2d_4/bias:0' shape=(192,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/batch_normalization_5/gamma:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/batch_normalization_5/beta:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/batch_normalization_5/moving_mean:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/batch_normalization_5/moving_variance:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/conv2d_5/kernel:0' shape=(9, 1, 64, 64) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/conv2d_5/bias:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/batch_normalization_6/gamma:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/batch_normalization_6/beta:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/batch_normalization_6/moving_mean:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_2/sequential_2/batch_normalization_6/moving_variance:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/conv_temporal_graphical_3/conv2d_6/kernel:0' shape=(1, 1, 64, 192) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/conv_temporal_graphical_3/conv2d_6/bias:0' shape=(192,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/batch_normalization_7/gamma:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/batch_normalization_7/beta:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/batch_normalization_7/moving_mean:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/batch_normalization_7/moving_variance:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/conv2d_7/kernel:0' shape=(9, 1, 64, 64) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/conv2d_7/bias:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/batch_normalization_8/gamma:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/batch_normalization_8/beta:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/batch_normalization_8/moving_mean:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_3/sequential_3/batch_normalization_8/moving_variance:0' shape=(64,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_5/conv2d_10/kernel:0' shape=(1, 1, 64, 128) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_5/conv2d_10/bias:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_5/batch_normalization_11/gamma:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_5/batch_normalization_11/beta:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_5/batch_normalization_11/moving_mean:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_5/batch_normalization_11/moving_variance:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/conv_temporal_graphical_4/conv2d_8/kernel:0' shape=(1, 1, 64, 384) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/conv_temporal_graphical_4/conv2d_8/bias:0' shape=(384,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/batch_normalization_9/gamma:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/batch_normalization_9/beta:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/batch_normalization_9/moving_mean:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/batch_normalization_9/moving_variance:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/conv2d_9/kernel:0' shape=(9, 1, 128, 128) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/conv2d_9/bias:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/batch_normalization_10/gamma:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/batch_normalization_10/beta:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/batch_normalization_10/moving_mean:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_4/sequential_4/batch_normalization_10/moving_variance:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/conv_temporal_graphical_5/conv2d_11/kernel:0' shape=(1, 1, 128, 384) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/conv_temporal_graphical_5/conv2d_11/bias:0' shape=(384,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/batch_normalization_12/gamma:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/batch_normalization_12/beta:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/batch_normalization_12/moving_mean:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/batch_normalization_12/moving_variance:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/conv2d_12/kernel:0' shape=(9, 1, 128, 128) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/conv2d_12/bias:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/batch_normalization_13/gamma:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/batch_normalization_13/beta:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/batch_normalization_13/moving_mean:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_5/sequential_6/batch_normalization_13/moving_variance:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/conv_temporal_graphical_6/conv2d_13/kernel:0' shape=(1, 1, 128, 384) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/conv_temporal_graphical_6/conv2d_13/bias:0' shape=(384,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/batch_normalization_14/gamma:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/batch_normalization_14/beta:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/batch_normalization_14/moving_mean:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/batch_normalization_14/moving_variance:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/conv2d_14/kernel:0' shape=(9, 1, 128, 128) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/conv2d_14/bias:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/batch_normalization_15/gamma:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/batch_normalization_15/beta:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/batch_normalization_15/moving_mean:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_6/sequential_7/batch_normalization_15/moving_variance:0' shape=(128,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_9/conv2d_17/kernel:0' shape=(1, 1, 128, 256) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_9/conv2d_17/bias:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_9/batch_normalization_18/gamma:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_9/batch_normalization_18/beta:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_9/batch_normalization_18/moving_mean:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_9/batch_normalization_18/moving_variance:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/conv_temporal_graphical_7/conv2d_15/kernel:0' shape=(1, 1, 128, 768) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/conv_temporal_graphical_7/conv2d_15/bias:0' shape=(768,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/batch_normalization_16/gamma:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/batch_normalization_16/beta:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/batch_normalization_16/moving_mean:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/batch_normalization_16/moving_variance:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/conv2d_16/kernel:0' shape=(9, 1, 256, 256) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/conv2d_16/bias:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/batch_normalization_17/gamma:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/batch_normalization_17/beta:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/batch_normalization_17/moving_mean:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_7/sequential_8/batch_normalization_17/moving_variance:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/conv_temporal_graphical_8/conv2d_18/kernel:0' shape=(1, 1, 256, 768) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/conv_temporal_graphical_8/conv2d_18/bias:0' shape=(768,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/batch_normalization_19/gamma:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/batch_normalization_19/beta:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/batch_normalization_19/moving_mean:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/batch_normalization_19/moving_variance:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/conv2d_19/kernel:0' shape=(9, 1, 256, 256) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/conv2d_19/bias:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/batch_normalization_20/gamma:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/batch_normalization_20/beta:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/batch_normalization_20/moving_mean:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_8/sequential_10/batch_normalization_20/moving_variance:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/conv_temporal_graphical_9/conv2d_20/kernel:0' shape=(1, 1, 256, 768) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/conv_temporal_graphical_9/conv2d_20/bias:0' shape=(768,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/batch_normalization_21/gamma:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/batch_normalization_21/beta:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/batch_normalization_21/moving_mean:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/batch_normalization_21/moving_variance:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/conv2d_21/kernel:0' shape=(9, 1, 256, 256) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/conv2d_21/bias:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/batch_normalization_22/gamma:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/batch_normalization_22/beta:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/batch_normalization_22/moving_mean:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/st_gcn_9/sequential_11/batch_normalization_22/moving_variance:0' shape=(256,) dtype=float32>, 
<tf.Variable 'model/stgcn_var/conv2d_22/kernel:0' shape=(1, 1, 256, 10) dtype=float32>, 
<tf.Variable 'model/stgcn_var/conv2d_22/bias:0' shape=(10,) dtype=float32>]